In [1]:
from bokeh.embed import components
from bokeh.io import output_notebook, show
from bokeh.plotting.figure import Figure
import numpy as np
output_notebook()

Loading BokehJS ...

In [2]:
x = np.linspace(0, 100, 11)
y1 = np.random.randn(11)
y2 = np.random.randn(11)
y3 = np.random.randn(11)

In [3]:
x

array([  0.,  10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

In [4]:
y1

array([ 1.70942633,  0.05128078, -0.39044929, -1.1464359 , -1.03742517,
       -0.41068952,  0.790034  ,  1.02702431,  0.35897633, -1.19757308,
        0.12617111])

In [5]:
y2

array([ 1.18414609, -0.03085089, -1.26604334, -0.503521  , -1.78568738,
       -2.64521981, -0.23341972, -0.90815206, -0.88204462,  0.43318265,
        0.87561114])

In [6]:
p = Figure(title='SUPER Simple Notebook Demo', plot_width=600, plot_height=200, sizing_mode='scale_width')
p.title.align = 'center'
p.title.text_font_size = '15pt'
p.line(x, y1, color='red', alpha=1, muted_alpha=0.2, legend='A')
p.line(x, y2, alpha=1, muted_alpha=0.2, legend='B')
p.circle(x, y3, color='purple', alpha=1, muted_alpha=0.2, legend='C')
p.line(x, y3, color='purple', alpha=1, muted_alpha=0.2, legend='C')
p.xaxis.axis_label = 'X Values'
p.yaxis.axis_label = 'Randomly Generated Values'
p.xgrid.grid_line_alpha = 1
p.xgrid.grid_line_dash = [3,7]
p.legend.click_policy = 'mute'
p.legend.background_fill_alpha = 0.8
p.toolbar.logo = None
show(p, notebook_handle=True)

In [7]:
script, div = components(p)

In [8]:
print(script)


<script type="text/javascript">
  (function() {
    var fn = function() {
      Bokeh.safely(function() {
        (function(root) {
          function embed_document(root) {
            
          var docs_json = '{"ed726084-e61c-46c1-890a-67f2aeca1f9d":{"roots":{"references":[{"attributes":{"line_alpha":0.1,"line_color":"#1f77b4","x":{"field":"x"},"y":{"field":"y"}},"id":"1040","type":"Line"},{"attributes":{"line_alpha":0.2,"line_color":"#1f77b4","x":{"field":"x"},"y":{"field":"y"}},"id":"1055","type":"Line"},{"attributes":{"data_source":{"id":"1084","type":"ColumnDataSource"},"glyph":{"id":"1085","type":"Line"},"hover_glyph":null,"muted_glyph":{"id":"1087","type":"Line"},"nonselection_glyph":{"id":"1086","type":"Line"},"selection_glyph":null,"view":{"id":"1089","type":"CDSView"}},"id":"1088","type":"GlyphRenderer"},{"attributes":{"line_alpha":0.2,"line_color":"#1f77b4","x":{"field":"x"},"y":{"field":"y"}},"id":"1041","type":"Line"},{"attributes":{"data_source":{"id":"1052","type":"C

In [9]:
print(div)


<div class="bk-root" id="24187609-2050-41d3-9f8a-6090ae8e5513" data-root-id="1003"></div>


<h1 style="text-align:center"><a href="https://bokeh.pydata.org/en/latest/docs/gallery.html">Link: Demo Gallery</a></h1>